// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmD7SwPmo5PtuDg4Jm_OEA0HivgBVE4a0',
    appId: '1:567819550700:web:7889fc90a38da96b948ac9',
    messagingSenderId: '567819550700',
    projectId: 'food-app-6e8da',
    authDomain: 'food-app-6e8da.firebaseapp.com',
    storageBucket: 'food-app-6e8da.firebasestorage.app',
    measurementId: 'G-EH67K120M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW4JXWrGvP_6p1m5DPgwW7MIcTga1il7w',
    appId: '1:567819550700:android:4d3bd1f197a80e16948ac9',
    messagingSenderId: '567819550700',
    projectId: 'food-app-6e8da',
    storageBucket: 'food-app-6e8da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlaZYXsKpPSxqdyxYux1GhebLs6fZF7hE',
    appId: '1:567819550700:ios:aab04758ea222306948ac9',
    messagingSenderId: '567819550700',
    projectId: 'food-app-6e8da',
    storageBucket: 'food-app-6e8da.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlaZYXsKpPSxqdyxYux1GhebLs6fZF7hE',
    appId: '1:567819550700:ios:aab04758ea222306948ac9',
    messagingSenderId: '567819550700',
    projectId: 'food-app-6e8da',
    storageBucket: 'food-app-6e8da.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmD7SwPmo5PtuDg4Jm_OEA0HivgBVE4a0',
    appId: '1:567819550700:web:bba19bda31d847fd948ac9',
    messagingSenderId: '567819550700',
    projectId: 'food-app-6e8da',
    authDomain: 'food-app-6e8da.firebaseapp.com',
    storageBucket: 'food-app-6e8da.firebasestorage.app',
    measurementId: 'G-G4GLCZ6NHM',
  );

}